// <auto-generated />
using System;
using EXAMcsharp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EXAMcsharp.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20190528194536_3migrations")]
    partial class _3migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EXAMcsharp.Models.Actvty", b =>
                {
                    b.Property<int>("ActvtyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Coordinator")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Duration")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("UserId");

                    b.HasKey("ActvtyId");

                    b.HasIndex("UserId");

                    b.ToTable("Actvtys");
                });

            modelBuilder.Entity("EXAMcsharp.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActvtyId");

                    b.Property<int>("UserId");

                    b.HasKey("MembershipId");

                    b.HasIndex("ActvtyId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("EXAMcsharp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ComparePassword")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EXAMcsharp.Models.Actvty", b =>
                {
                    b.HasOne("EXAMcsharp.Models.User", "Creator")
                        .WithMany("Actvtys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EXAMcsharp.Models.Membership", b =>
                {
                    b.HasOne("EXAMcsharp.Models.Actvty", "Actvty")
                        .WithMany("Memberships")
                        .HasForeignKey("ActvtyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EXAMcsharp.Models.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
